services:
  - type: web
    name: django-rest-assignment
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rest_project.wsgi:application --chdir rest_project --preload --workers=3 --threads=2 --timeout=120
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
    healthCheckPath: /
    autoDeploy: true
